# Site settings
title: "News from London"
email: ryan@mijingo.com
description: "A daily journal by Edward Hyde."
baseurl: "/london-news"
url: "http://localhost:4000"

# Build settings
markdown: rdiscount
rdiscount:
 extensions: [smart]
permalink: /articles/:title
paginate: 3